services:

  backend:
    build:
      context: ./backend
    ports:
      - "9999:${PORT:-9999}"
    environment:
      - PORT=${PORT:-9999}
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=${FRONTEND_URL:-https://rekcal.kinavity.com}
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"

volumes:
  mongodb_data:
